export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const SET_PRODUCT = 'SET_PRODUCT'
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';


export const FETCH_PRODUCTS_HOME_PAGE_START = 'FETCH_PRODUCTS_HOME_PAGE';
export const SET_PRODUCTS_HOME_PAGE = 'SET_PRODUCTS_HOME_PAGE';
export const FETCH_PRODUCTS_HOME_PAGE_FAILED = 'FETCH_PRODUCTS_HOME_PAGE_FAILED';

export const FETCH_PRODUCTS_SEARCH_PAGE_START = 'FETCH_PRODUCTS_SEARCH_PAGE';
export const SET_PRODUCTS_SEARCH_PAGE = 'SET_PRODUCTS_SEARCH_PAGE';
export const FETCH_PRODUCTS_SEARCH_PAGE_FAILED = 'FETCH_PRODUCTS_SEARCH_PAGE_FAILED';


export const UPDATE_PRODUCER = 'UPDATE_PRODUCER';
export const UPDATE_RAM_MEMORY = 'UPDATE_RAM_MEMORY';
export const UPDATE_PROCESSOR = 'UPDATE_PROCESSOR';
export const UPDATE_GRAPHIC_CARD = 'UPDATE_GRAPHIC_CARD';
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
export const UPDATE_MIN_PRICE = 'UPDATE_MIN_PRICE';
export const UPDATE_MAX_PRICE = 'UPDATE_MAX_PRICE';




