export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const SET_PRODUCT = 'SET_PRODUCT'
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';


export const FETCH_PRODUCTS_HOME_PAGE_START = 'FETCH_PRODUCTS_HOME_PAGE';
export const SET_PRODUCTS_HOME_PAGE = 'SET_PRODUCTS_HOME_PAGE';
export const FETCH_PRODUCTS_HOME_PAGE_FAILED = 'FETCH_PRODUCTS_HOME_PAGE_FAILED';


